# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Push Nodejs App to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: travel-app
      PROJECT_ID: gcp-wow-food-wlx-mpp-psh-dev
      SERVICE_NAME: travel-app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_Default_credentials: true
      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            token:projects/527559480534/secrets/secret-name/versions/1
      - name: Build Docker Image
        env:
          TOKEN: ${{ steps.secrets.outputs.token }}
        run: docker build --build-arg name=production -t gcr.io/${{ env.PROJECT_ID }}/$IMAGE_NAME:latest .
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker australia-southeast1-docker.pkg.dev --quiet
      - name: Push Docker Image to Container Registry ( GCR )
        run: |-
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Deploy
        run: |
          gcloud run deploy $IMAGE_NAME \
          --region australia-southeast1 \
          --image gcr.io/$PROJECT_ID/$IMAGE_NAME \
          --platform managed \
          --allow-unauthenticated \
          --project $PROJECT_ID
